language: node_js
node_js:
- "6.9"
dist: trusty
before_script:
- npm install -g @angular/cli
- npm install -g firebase-tools
script:
- ls
- npm install
- ng build
- ls
after_success:
- ./deploy.sh m4m-code-heroes
cache:
  directories:
    - $(npm config get prefix)/bin/@angular/cli
    - $(npm config get prefix)/bin/firebase-tools
    - node_modules
