language: node_js
node_js:
- '6.9'
dist: trusty
before_script:
- npm list -g @angular/cli --depth=0 || npm install -g @angular/cli
- npm list -g firebase-tools --depth=0 || npm install -g firebase-tools
script:
- ls
- npm install
- ng build
after_success:
- ./deploy.sh m4m-code-heroes
cache:
  directories:
  - $(npm config get prefix)/bin/@angular/cli
  - $(npm config get prefix)/bin/firebase-tools
  - node_modules
notifications:
  email: false
  slack:
    secure: nv8adxKjGViEcHGsCtUH1ubjVDTBWlviG1JRQjHZtHNwb1QONxkftENcdQA5egLlcYh3dTkT5DJWMo1Dl/pxHjH4lRG+emAJ+T0nblSABXPY90roAzH26S0iIHad0PGw2LDkNwFlrBtavf5Oc14/ZBflpRgnEvTuMysgY5MduqY9/6HrNH2F6Nm3jYmfb7G5rJI5QmaVkiewYulv1P2Tq/QQEwcMgCar8+76AHpfynZykbwL57mpXVrQ2nCDmheeQhWbNXU7IwtqDTRu0Y6VGvZQIQok2jeyr34Hn9GxRu2K2DrWySqv4/41PRqD9qgrY9F7QMci1QbWYdRc5RNnW/Yw9sCu89FXtxSWjunK9ImkZRAE6TWGz9UrTtC9XL7cWTPsZKdJczlZhNhwirddih7eQr/kwNBcmzrtpdlw69SGs85nO3faxHGfu26XMhNNvC7/ixm+agUqK4hiyQv3n9aJ363UQV9/7QYs5y/TlU7tMp3nTtLRdeQszhIjn79UOWFJMMcmxD3bJlSEg6CqZj/YrmY8nvCG38nlM/6uAvA7LccjOHWb4y8GlfWUD18GAT9GcdXkxvh4pzPYwdRuvvwLgQZdSCdGpi5MYNEE39QE6dxJ2osJ5Qv6x29ZhkgpEaT1LJkdQBY0tMpx0oLMxG8L33OlgQ+54xSfsLU6ME8=
  webhooks: https://coders.move4mobile.com/webhooks/travis
