language: node_js
node_js:
- node
dist: trusty
before_script:
- npm list -g angular-cli --depth=0 || npm install -g angular-cli
- npm list -g firebase-tools --depth=0 || npm install -g firebase-tools
script:
- npm install
- ng build
# after_success:
# - chmod +x travis_scripts/deploy.sh
# - ./travis_scripts/deploy.sh crossover-app
# cache:
#   directories:
#     - $(npm config get prefix)/bin/cordova
#     - $(npm config get prefix)/bin/ionic
#     - $(npm config get prefix)/bin/firebase-tools
#     - node_modules
